### ISSUE TITLE
User Authentication verify OTP bug

### ISSUE THREAD

**Issue by vaibhav540** [vaibhav540/Democracy-Data_035#1]
# Bug Reports
***Bug: User unable to log in with valid credentials***

# Description: Users are unable to log in even with valid email and password.
$Steps to Reproduce:$

 `Go to the login page.`
 Enter a valid email and password.
` Click the "Login" button.`
Expected Behavior: The user should be logged in and redirected to the dashboard.
Actual Behavior: The user remains on the login page with no error message.

Environment: Windows 10, Chrome Version 91
Bug: Password reset email not being sent

# Description: Users are not receiving the password reset email.
$Steps to Reproduce:$

1.  Go to the "Forgot Password" page.

2.  Enter a registered email address.

3.  Click the "Send Reset Link" button.

***Expected Behavior:*** A password reset email should be sent to the user's email address.
Actual Behavior: No email is received by the user.

Environment: macOS, Safari Version 14

$Feature Requests$
$Feature: Implement social login options$

# Description: Add options for users to log in using their social media accounts.

***User Story: As a user, I want to log in using my Google or Facebook account so that I don't have to create a new account.
Acceptance Criteria:***

*  Add "Login with Google" and "Login with Facebook" buttons on the login page.
*  Users should be able to log in using their Google or Facebook credentials.
 * The user's social media profile information should be saved to the database.

//Enhancements//
----Enhancement: Improve error messages during login----

# Description: Provide more descriptive error messages when login fails.

-Current Behavior: Generic error message "Login failed".

-Expected Behavior: Specific error messages like "Incorrect password" or "User not found".

***Steps to Implement:***
 1. Update the backend to send specific error messages.
2.  Update the frontend to display these error messages to the user.
3. Enhancement: Session timeout warning

# Description: Warn users before their session times out.

***User Story: As a user, I want to be warned before my session expires so that I can save my work.***

Acceptance Criteria:

*  Display a warning message 5 minutes before session expiration.
*  Provide an option for users to extend their session.
*  Redirect users to the login page if the session expires.

**Comment by Mayank1st** [comment]
Overview:
This request addresses an issue where the navbar was misaligned on smaller screens, causing a poor user experience. The fix ensures that the navbar aligns correctly across all devices.

Changes:

- [x] Responsiveness Added
- [x] Backend Part-1 added
Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #1

**Comment by Mayank1st** [comment]
Overview:
This request addresses an issue where the navbar was misaligned on smaller screens, causing a poor user experience. The fix ensures that the Authentication aligns correctly across all devices.

Changes:

- [x]  Responsiveness Added
- [x]  Backend Part-2 added


Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #1

![image](https://github.com/user-attachments/assets/5eafb016-6f1d-4899-964f-0ba266b56355)
