### ISSUE TITLE
After Navbar Part

### ISSUE THREAD

**Issue by vaibhav540** [vaibhav540/Democracy-Data_035#6]
Description:

I'm experiencing an issue with the navbar header on mobile devices. It appears to be misaligned and does not respond correctly to user interactions.

Steps to Reproduce:

Open the application on a mobile device or use responsive design mode in a desktop browser.
Observe the navbar header on various screen sizes.
Interact with the navbar links or dropdown menus.
Expected Behavior:

The navbar should be properly aligned and responsive on mobile devices.
Navbar links and dropdown menus should be functional and accessible.
Actual Behavior:

The navbar header appears misaligned and does not fit within the viewport on mobile devices.
Dropdown menus and links are either not visible or do not function as intended.
Additional Information:

Browser/Device: The issue occurs on both iOS and Android devices, as well as in Chrome and Firefox.

Screenshots: [Attach any screenshots if available]

Code Snippet:

jsx
Copy code
// Example code snippet of the navbar component
<nav className="navbar">
  <div className="logo">MyApp</div>
  <ul className="nav-links">
    <li><a href="#home">Home</a></li>
    <li><a href="#about">About</a></li>
    <li className="dropdown">
      <a href="#services">Services</a>
      <ul className="dropdown-menu">
        <li><a href="#web">Web Development</a></li>
        <li><a href="#mobile">Mobile Development</a></li>
      </ul>
    </li>
  </ul>
</nav>
css
Copy code
/* Example CSS for the navbar */
.navbar {
  position: fixed;
  top: 0;
  width: 100%;
  background-color: #fff;
  z-index: 1000;
}

.nav-links {
  display: flex;
  justify-content: space-between;
}

.dropdown-menu {
  display: none;
  position: absolute;
  top: 100%;
}

.dropdown:hover .dropdown-menu {
  display: block;
}
Potential Solution:

Responsive Design: Review and adjust media queries to ensure the navbar layout adapts correctly to mobile screens.
CSS Adjustments: Verify padding, margins, and positioning for proper alignment and spacing.
JavaScript Functionality: Ensure dropdown menus and links are properly initialized and functioning.

**Comment by Mayank1st** [comment]
Overview:
This request addresses an issue where the navbar was misaligned on smaller screens, causing a poor user experience. The fix ensures that the navbar aligns correctly across all devices.

Changes:

- [x]  Responsiveness Added
- [x]  Backend and frontend of authentication merged successfully.

Request for Review:
Please review the changes and provide any feedback or suggestions for improvement. Thank you!
References:
Related issue: #6


![image](https://github.com/user-attachments/assets/a5c091ca-dd30-42a1-9312-fd9d1de5b3b5)
